config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  require 'sidekiq/web'

  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :contacts, only: [:new, :create, :index] do
    collection { post :import }
  end
  resources :csv_uploads, only: [:new, :create, :index, :destroy]
  resources :csv_mapper, only: :new
end

app/models/csv_upload.rb
class CsvUpload < ApplicationRecord

  include RailsStateMachine::Model


  state_machine do
    state :waiting, initial: true
    state :processing
    state :finished
    state :failed
    state :empty

    event :start_processing do
      transitions from: :waiting, to: :processing
    end

    event :contact_imported do
      transitions from: :processing, to: :finished
    end

    event :nothing_is_good do
      transitions from: :processing, to: :failed
    end

    event :no_contacts_available do
      transitions from: :processing, to: :empty
    end
  end

  def self.state_colors(state)
    colors = {
      waiting: :secondary,
      processing: :primary,
      finished: :success,
      failed: :danger,
      empty: :info,
    }
    return colors[state.to_sym]
  end

  belongs_to :user

  has_one_attached :csv_file
  validates :csv_file, presence: true
  validate :correct_csv_mime_type

  after_create_commit {broadcast_prepend_to 'csv_uploads'}
  after_update_commit {broadcast_replace_to 'csv_uploads'}
  after_destroy_commit {broadcast_remove_to 'csv_uploads'}

  default_scope {order("created_at DESC")}

  private

  def correct_csv_mime_type
    # correct_csv_mime_type.
    #
    # checks csv_mime_type when being uploaded using a form
    #
    if csv_file.attached? && !csv_file.content_type.in?(%w(text/csv))
      errors.add(:csv_file, 'Only accept CSV files for the moment')
    end
  end
end

app/controllers/csv_uploads_controller.rb
class CsvUploadsController < ApplicationController
  before_action :authenticate_user!

  def new
    @csv_upload = current_user.csv_uploads.new()
  end

  def index
    @pagy, @csv_uploads = pagy(current_user.csv_uploads.all)
  end
  
  def create
    @csv_upload = current_user.csv_uploads.new(csv_params)
    if @csv_upload.save
      redirect_to new_csv_mapper_path(id: @csv_upload), notice: "File accepted"
    else
      render :new
    end
  end

  def destroy
    @csv_upload = current_user.csv_uploads.find(params[:id])
    redirect_to csv_uploads_path, notice: 'File deleted succesfully' if @csv_upload.destroy
  end

 private
  def csv_params
    if params[:csv_upload].present?
      params.require(:csv_upload).permit(:csv_file)
    end
  end
end

app/helpers/csv_uploads_helper.rb
module CsvUploadsHelper
end

app/views/csv_uploads/_csv_upload.html.erb
<%= turbo_frame_tag dom_id(csv_upload) do %>
  <div class="col">
    <div class="card m-3 border-<%= CsvUpload.state_colors(csv_upload.state)%> " style="width: 18rem; height: 400px;">
      <div class="card-header bg-transparent border-<%= CsvUpload.state_colors(csv_upload.state) %>">Filename: <%= truncate(csv_upload.csv_file.filename.to_s, length: 23) %></div>
      <div class="card-body text-<%= CsvUpload.state_colors(csv_upload.state) %> ">
        <h5 class="card-title">State: <%= csv_upload.state %></h5>
        <p class="card-text">Download: <%= link_to csv_upload.csv_file.filename, rails_blob_path(csv_upload.csv_file, disposition: 'attachment') %></p>
        <p class="card-text"> <%= link_to "Process "+csv_upload.csv_file.filename.to_s, new_csv_mapper_path(id: csv_upload.id), class: "btn btn-primary" if csv_upload.state == "waiting" %></p>
        <p class="card-text"> <%= link_to "Delete", csv_upload_path(id: csv_upload.id), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?"  } %></p>
      </div>
      <div class="card-footer bg-transparent border-<%= CsvUpload.state_colors(csv_upload.state) %>">Uploaded: <%= time_ago_in_words(csv_upload.created_at) %> ago </div>
    </div>
  </div>
<% end %>

app/views/csv_uploads/_csv_upload_deck.html.erb
  <%= render csv_uploads %>

app/views/csv_uploads/_form.html.erb
<%= form_with model: csv_upload  do |form| %>
  <% if csv_upload.errors.any? %>
    <div class="alert alert-danger">
      <% csv_upload.errors.full_messages.each do |message| %>
        <div><%= message %> </div>
      <% end %>
    </div>
  <% end %>
  <%= form.file_field :csv_file, class: "form-control" %>
  <%= form.submit "Upload", class: "btn btn-outline-primary" %>
<% end %>

app/views/csv_uploads/index.html.erb
<h1 class="display-5 text-center"> Your files</h1>
<%= pagy_bootstrap_nav(@pagy).html_safe %>
<%= turbo_stream_from 'csv_uploads' %>
<%= turbo_frame_tag 'csv_uploads', class: "row row-cols-1 row-cols-md-2 g-4" do  %>
  <%= render @csv_uploads %>
<% end %>
<%= pagy_bootstrap_nav(@pagy).html_safe %>

app/views/csv_uploads/new.html.erb
<h1 class="display-5 text-center">Upload a new .CSV file with contacts</h1>
<%= render "form", csv_upload: @csv_upload %>