config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  require 'sidekiq/web'

  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :contacts, only: [:new, :create, :index] do
    collection { post :import }
  end
  resources :csv_uploads, only: [:new, :create, :index, :destroy]
  resources :csv_mapper, only: :new
end

app/views/shared/_footer.html.erb
<footer class="fixed-bottom text-center border-top">
  <div class="container">
    Contact Importer by David Orejuela @<%= Time.now.year %>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg border-bottom ">
  <div class="container">
    <%= link_to root_path, class: "nav_logo" do %>
      <%= image_tag("Logo.png", width: 70) %>
      <h1 class="navbar-brand display-4 font-weight-bold text-dark">Contact Importer</h1>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="align-middle collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto navbar-right">
        <% if user_signed_in? %>
          <li>
            <p class="navbar-brand">
            Hi, <%= link_to("@"+current_user.email, edit_user_registration_path)%>
            </p>
          </li>
          <li>
            <p>
            <%= link_to('My imported contacts', contacts_path, class: "navbar-brand btn btn-outline-primary") %>
            </p>
          </li>
          <li>
            <p>
            <%= link_to('My imported files', csv_uploads_path, class: "navbar-brand btn btn-outline-success") %>
            </p>
          </li>
          <li>
            <p>
            <%= link_to("Sign out", destroy_user_session_path, method: :delete, class: "navbar-brand btn btn-outline-danger") %>
            </p>
          </li>
        <% else %>
          <li>
            <p>
            <%= link_to('Sign in', new_user_session_path, class: "navbar-brand btn btn-outline-primary") %></p></li>
          <li>
            <p>
            <%= link_to('Sign up', new_user_registration_path, class: "navbar-brand btn btn-outline-success") %>
            </p>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>